version: "2"

run:
  timeout: 10m10s

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace

  exclusions:
    rules:
      - linters:
          - gosec
        text: "integer overflow conversion"
        path: cidr/

formatters:
  enable:
    - gofmt
    - goimports
